### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by DionnyV** [angryjack/ubans.pro#2]
1. When saving changes to a user without changing the password, it is replaced in the database by blank text.

1. Permanent checkbox (expired = 0) for admin time not working (not inserted in db).

1. Can't use 'flag for all servers' (access table from db) because we need to select a Privileges from the dropdown list (not 'none' option).

1. There is no option to delete a server.

1. There is no option to delete a privileges.

**Comment by angryjack** [comment]
Hi, thanks for reporting. 
I'll ckeck.
